<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-GS0ADV1" name="com.mindtree.tests.BookReturnTicketTest" tests="5" failures="0" timestamp="24 May 2019 15:59:20 GMT" time="59.229" errors="1">
  <testcase name="loginMethod" time="31.625" classname="com.mindtree.tests.BookReturnTicketTest"/>
  <testcase name="flightFinderMethod" time="27.601" classname="com.mindtree.tests.BookReturnTicketTest"/>
  <testcase name="mtSelectFlightDataMethod" time="0.003" classname="com.mindtree.tests.BookReturnTicketTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.mindtree.pages.SelectFlightPage.selectParisToLondon(SelectFlightPage.java:24)
at com.mindtree.tests.BookReturnTicketTest.mtSelectFlightDataMethod(BookReturnTicketTest.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- mtSelectFlightDataMethod -->
  <testcase name="mtBookFlightDataMethod" time="0.000" classname="com.mindtree.tests.BookReturnTicketTest">
    <skipped/>
  </testcase> <!-- mtBookFlightDataMethod -->
  <testcase name="mtFlightConfirmationDataMethod" time="0.000" classname="com.mindtree.tests.BookReturnTicketTest">
    <skipped/>
  </testcase> <!-- mtFlightConfirmationDataMethod -->
</testsuite> <!-- com.mindtree.tests.BookReturnTicketTest -->
